//! pattern_matcher.rs
//! System 1 – Fast, automatic, associative reasoning.
//! Implements Kahneman's System 1: intuitive, heuristic, parallel pattern matching.
//! This module provides rapid, low-latency responses based on learned associations.

use std::collections::HashMap;

/// A stimulus pattern that triggers System 1 responses.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Stimulus {
    /// The raw input string (e.g., user message).
    pub content: String,
    /// Optional contextual tags (e.g., "urgent", "greeting").
    pub tags: Vec<String>,
}

/// A response generated by System 1.
#[derive(Debug, Clone, PartialEq)]
pub struct Response {
    /// The textual response.
    pub text: String,
    /// Confidence score (0.0 to 1.0) based on pattern match strength.
    pub confidence: f64,
    /// The stimulus that triggered this response (for traceability).
    pub triggered_by: Stimulus,
}

/// The Pattern Matcher – a learned association network.
pub struct PatternMatcher {
    /// Maps stimulus patterns to their associated responses.
    associations: HashMap<Stimulus, Response>,
    /// Fallback response when no pattern matches.
    fallback: String,
}

impl PatternMatcher {
    /// Creates a new, empty pattern matcher with a default fallback.
    pub fn new() -> Self {
        Self {
            associations: HashMap::new(),
            fallback: String::from("I need a moment to think about that."),
        }
    }

    /// Sets a custom fallback response.
    pub fn with_fallback(mut self, fallback: impl Into<String>) -> Self {
        self.fallback = fallback.into();
        self
    }

    /// Learns a new association between a stimulus and a response.
    pub fn learn(&mut self, stimulus: Stimulus, response: Response) {
        self.associations.insert(stimulus, response);
    }

    /// Matches a stimulus to the best known response.
    /// Currently uses exact matching; can be extended to fuzzy/semantic matching.
    pub fn match_stimulus(&self, stimulus: &Stimulus) -> Response {
        if let Some(canned) = self.associations.get(stimulus) {
            return canned.clone();
        }

        // Partial match: try matching by tags only (heuristic)
        for (known, resp) in &self.associations {
            if !known.tags.is_empty() && known.tags.iter().any(|tag| stimulus.tags.contains(tag)) {
                return Response {
                    text: resp.text.clone(),
                    confidence: 0.5, // lower confidence for partial match
                    triggered_by: stimulus.clone(),
                };
            }
        }

        // Fallback
        Response {
            text: self.fallback.clone(),
            confidence: 0.0,
            triggered_by: stimulus.clone(),
        }
    }

    /// Returns the number of learned associations.
    pub fn len(&self) -> usize {
        self.associations.len()
    }

    /// Returns true if no associations have been learned.
    pub fn is_empty(&self) -> bool {
        self.associations.is_empty()
    }
}

impl Default for PatternMatcher {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn greeting_stimulus() -> Stimulus {
        Stimulus {
            content: "Hello".to_string(),
            tags: vec!["greeting".to_string()],
        }
    }

    fn greeting_response() -> Response {
        Response {
            text: "Hi there!".to_string(),
            confidence: 1.0,
            triggered_by: greeting_stimulus(),
        }
    }

    #[test]
    fn test_exact_match() {
        let mut matcher = PatternMatcher::new();
        let stim = greeting_stimulus();
        let resp = greeting_response();
        matcher.learn(stim.clone(), resp.clone());

        let result = matcher.match_stimulus(&stim);
        assert_eq!(result.text, "Hi there!");
        assert_eq!(result.confidence, 1.0);
    }

    #[test]
    fn test_fallback() {
        let matcher = PatternMatcher::new().with_fallback("I don't understand.");
        let stim = Stimulus {
            content: "Blarg".to_string(),
            tags: vec![],
        };
        let result = matcher.match_stimulus(&stim);
        assert_eq!(result.text, "I don't understand.");
        assert_eq!(result.confidence, 0.0);
    }

    #[test]
    fn test_partial_tag_match() {
        let mut matcher = PatternMatcher::new();
        let stim1 = Stimulus {
            content: "I need help".to_string(),
            tags: vec!["urgent".to_string()],
        };
        let resp1 = Response {
            text: "Help is on the way.".to_string(),
            confidence: 1.0,
            triggered_by: stim1.clone(),
        };
        matcher.learn(stim1, resp1);

        let stim2 = Stimulus {
            content: "Something is wrong".to_string(),
            tags: vec!["urgent".to_string()],
        };
        let result = matcher.match_stimulus(&stim2);
        assert_eq!(result.text, "Help is on the way.");
        assert_eq!(result.confidence, 0.5);
    }
}
