;;; counterfactual_simulator.lisp
;;; System 2 – Counterfactual reasoning and "what-if" simulation.
;;; Implements the decoupling operation described by Stanovich (2010).

(defpackage :revarie-system-two
  (:use :common-lisp)
  (:export :create-world
           :make-counterfactual
           :evaluate
           :compare-worlds
           :possible-world-p))

(in-package :revarie-system-two)

;;; ---------------------------------------------------------------------------
;;; Possible World Representation
;;; ---------------------------------------------------------------------------

(defstruct possible-world
  "A possible world is a set of facts and rules that differ from the actual world."
  (id (gensym "WORLD-") :type symbol)
  (facts (make-hash-table :test 'equal) :type hash-table)
  (rules nil :type list)
  (parent nil :type (or null possible-world)))

(defun create-world (&key facts rules)
  "Create a new possible world with the given facts and rules."
  (let ((world (make-possible-world)))
    (when facts
      (loop for (key . value) in facts
            do (setf (gethash key (possible-world-facts world)) value)))
    (when rules
      (setf (possible-world-rules world) rules))
    world))

(defun make-counterfactual (base-world &key altered-facts altered-rules)
  "Create a counterfactual world derived from BASE-WORLD.
   Performs a deep copy of the facts hash table to prevent state bleeding."
  (let ((new-world (copy-possible-world base-world))
        (new-facts (make-hash-table :test 'equal)))
    
    ;; Deep copy the existing facts
    (maphash (lambda (k v) (setf (gethash k new-facts) v))
             (possible-world-facts base-world))
    (setf (possible-world-facts new-world) new-facts)
    
    ;; Update metadata
    (setf (possible-world-parent new-world) base-world)
    (setf (possible-world-id new-world) (gensym "CF-"))
    
    ;; Apply alterations safely
    (when altered-facts
      (loop for (key . value) in altered-facts
            do (setf (gethash key (possible-world-facts new-world)) value)))
    (when altered-rules
      (setf (possible-world-rules new-world) altered-rules))
    new-world))

;;; ---------------------------------------------------------------------------
;;; Evaluation
;;; ---------------------------------------------------------------------------

(defgeneric evaluate (world query)
  (:documentation "Evaluate a query in a possible world."))

(defmethod evaluate ((world possible-world) (query string))
  "Simple evaluation: check if query matches any fact."
  (let ((facts (possible-world-facts world)))
    (maphash (lambda (k v)
               (when (search query k :test #'char-equal)
                 (return-from evaluate v)))
             facts)
    nil))

;;; ---------------------------------------------------------------------------
;;; Comparison
;;; ---------------------------------------------------------------------------

(defun compare-worlds (world1 world2)
  "Return a list of facts that differ between two worlds."
  (let ((diffs nil))
    (maphash (lambda (k v)
               (let ((other (gethash k (possible-world-facts world2) :not-found)))
                 (unless (equal v other)
                   (push (list k v other) diffs))))
             (possible-world-facts world1))
    diffs))

;;; Note: `possible-world-p` is automatically generated by `defstruct`, 
;;; so a manual defun is omitted to prevent compiler redefinition warnings.
