;;; markov_blanket.lisp
;;; Active Inference – Markov Blanket.
;;; Implements the conditional independence structure that defines the
;;; boundary between an agent's internal states and its environment.
;;; Based on Friston's Free Energy Principle.

(defpackage :revarie-active-inference
  (:use :common-lisp)
  (:export :make-markov-blanket
           :blanket-internal    ;; FIXED: Export correct accessors
           :blanket-sensory
           :blanket-active
           :update-sensory
           :update-active
           :update-internal
           :free-energy
           :blanket-p))

(in-package :revarie-active-inference)

;;; ---------------------------------------------------------------------------
;;; Markov Blanket Structure
;;; ---------------------------------------------------------------------------

;; FIXED: Renamed auto-constructor to %make-markov-blanket to avoid clash
(defstruct (markov-blanket (:constructor %make-markov-blanket) (:conc-name blanket-))
  "A Markov blanket partitions an agent's states into internal, sensory,
   and active states. Sensory and active states form the blanket that
   separates internal states from the external environment."
  (internal nil :type list)   ; Internal states (beliefs, hidden causes)
  (sensory nil :type list)    ; Sensory states (observations)
  (active nil :type list)     ; Active states (actions)
  (internal-dims 0 :type fixnum)
  (sensory-dims 0 :type fixnum)
  (active-dims 0 :type fixnum))

(defun make-markov-blanket (internal-dims sensory-dims active-dims)
  "Create a new Markov blanket with specified dimensions.
   Initializes all states to zero."
  (let ((blanket (%make-markov-blanket
                   :internal-dims internal-dims
                   :sensory-dims sensory-dims
                   :active-dims active-dims)))
    (setf (blanket-internal blanket) (make-list internal-dims :initial-element 0.0))
    (setf (blanket-sensory blanket) (make-list sensory-dims :initial-element 0.0))
    (setf (blanket-active blanket) (make-list active-dims :initial-element 0.0))
    blanket))

;;; ---------------------------------------------------------------------------
;;; State Updates
;;; ---------------------------------------------------------------------------

(defun update-sensory (blanket observation)
  "Update sensory states with a new observation."
  (when (not (= (length observation) (blanket-sensory-dims blanket)))
    (error "Observation dimension mismatch"))
  (setf (blanket-sensory blanket) (copy-list observation)))

(defun update-active (blanket action)
  "Update active states with a selected action."
  (when (not (= (length action) (blanket-active-dims blanket)))
    (error "Action dimension mismatch"))
  (setf (blanket-active blanket) (copy-list action)))

(defun update-internal (blanket new-internal)
  "Directly set internal states (used after inference)."
  (when (not (= (length new-internal) (blanket-internal-dims blanket)))
    (error "Internal state dimension mismatch"))
  (setf (blanket-internal blanket) (copy-list new-internal)))

;;; ---------------------------------------------------------------------------
;;; Free Energy Computation (Simplified)
;;; ---------------------------------------------------------------------------

(defun free-energy (blanket &key (sensory-precision 1.0) (internal-precision 1.0))
  "Compute the variational free energy for the current blanket state.
   F ≈ precision * (sensory surprise + internal complexity)."
  (let ((sensory-surprise 0.0)
        (internal-complexity 0.0))
    ;; Sensory surprise: -ln P(s|μ) under Gaussian assumption
    ;; Note: loop terminates safely when shortest list is exhausted
    (loop for s in (blanket-sensory blanket)
          for mu in (blanket-internal blanket) ; simplified: internal states predict sensory
          do (let ((pred-error (- s mu)))
               (incf sensory-surprise (* 0.5 sensory-precision pred-error pred-error))))
    ;; Internal complexity: KL divergence from prior (here simply L2 norm)
    (loop for mu in (blanket-internal blanket)
          do (incf internal-complexity (* 0.5 internal-precision mu mu)))
    (+ sensory-surprise internal-complexity)))

;;; FIXED: Removed manual `blanket-p` defun, as it's auto-generated by defstruct.

;;; ---------------------------------------------------------------------------
;;; Tests (FiveAM)
;;; ---------------------------------------------------------------------------

#+fiveam
(progn
  (defpackage :revarie-active-inference-tests
    (:use :common-lisp :fiveam :revarie-active-inference))
  (in-package :revarie-active-inference-tests)

  (def-suite active-inference-tests
    :description "Tests for Active Inference Markov blanket")
  (in-suite active-inference-tests)

  (test blanket-creation
    "Test creation of a Markov blanket."
    (let ((mb (make-markov-blanket 3 2 1)))
      (is (blanket-p mb))
      (is (= 3 (length (blanket-internal mb))))
      (is (= 2 (length (blanket-sensory mb))))
      (is (= 1 (length (blanket-active mb))))))

  (test sensory-update
    "Test updating sensory states."
    (let ((mb (make-markov-blanket 2 2 1)))
      (update-sensory mb '(1.0 0.5))
      (is (equal '(1.0 0.5) (blanket-sensory mb)))))

  (test active-update
    "Test updating active states."
    (let ((mb (make-markov-blanket 2 2 2)))
      (update-active mb '(0.8 -0.2))
      (is (equal '(0.8 -0.2) (blanket-active mb)))))

  (test internal-update
    "Test updating internal states."
    (let ((mb (make-markov-blanket 3 2 1)))
      (update-internal mb '(0.1 0.2 0.3))
      (is (equal '(0.1 0.2 0.3) (blanket-internal mb)))))

  (test free-energy-computation
    "Test that free energy is computed correctly."
    (let ((mb (make-markov-blanket 2 2 1)))
      (update-sensory mb '(1.0 0.0))
      (update-internal mb '(0.5 0.5))
      (let ((fe (free-energy mb)))
        (is (> fe 0.0)))))

  (run! 'active-inference-tests))
