name: Sync to Hugging Face Hub

on:
  push:
    branches: [Production] # Triggers only when you push to the production branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Logic: Pushes your local 'production' branch to the Space's 'main' branch
          git push --force https://ariartry:$HF_TOKEN@huggingface.co/spaces/ariartry/revarie-engine-v1 production:main
